name: Testing correct file structure

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-dev
    - name: Determine changed files
      id: files
      uses: jitterbit/get-changed-files@v1
    - name: Run pytest
      run: |
        ADDED_MODIFIED_FILES='${{ steps.files.outputs.added_modified }}' \
        REMOVED_FILES='${{ steps.files.outputs.removed }}' \
        poetry run pytest
